apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: apps
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        intent: apps
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: apps
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["m6i.2xlarge", "m6in.2xlarge", "m6a.2xlarge", "m5.2xlarge"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
      kubelet:
        clusterDNS: ["10.150.0.10"]
        maxPods: 58
  limits:
    cpu: 128
    memory: 512Gi
  disruption:
    expireAfter: 1440h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: apps
  namespace: kube-system
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "dev"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "dev"
  role: "node-karpenter-dev"
  tags:
    Name: "karpenter-node-dev-apps"
    Intent: "apps"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
  detailedMonitoring: true